# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import repository_pb2 as repository__pb2


class RepositoryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitializeRepository = channel.unary_unary(
                '/Repository/InitializeRepository',
                request_serializer=repository__pb2.InitializeRepositoryRequest.SerializeToString,
                response_deserializer=repository__pb2.InitializeRepositoryResponse.FromString,
                )


class RepositoryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitializeRepository(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RepositoryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitializeRepository': grpc.unary_unary_rpc_method_handler(
                    servicer.InitializeRepository,
                    request_deserializer=repository__pb2.InitializeRepositoryRequest.FromString,
                    response_serializer=repository__pb2.InitializeRepositoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Repository', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Repository(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitializeRepository(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Repository/InitializeRepository',
            repository__pb2.InitializeRepositoryRequest.SerializeToString,
            repository__pb2.InitializeRepositoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
