# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: repository.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10repository.proto\"\xc8\x01\n\x1bInitializeRepositoryRequest\x12\x36\n\x05\x66iles\x18\x01 \x03(\x0b\x32\'.InitializeRepositoryRequest.FilesEntry\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x14\n\x0c\x62\x61tch_number\x18\x03 \x01(\x05\x12\x19\n\x11num_total_batches\x18\x04 \x01(\x05\x1a,\n\nFilesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\"5\n\x1cInitializeRepositoryResponse\x12\x15\n\rrepository_id\x18\x01 \x01(\t2c\n\nRepository\x12U\n\x14InitializeRepository\x12\x1c.InitializeRepositoryRequest\x1a\x1d.InitializeRepositoryResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'repository_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INITIALIZEREPOSITORYREQUEST_FILESENTRY']._options = None
  _globals['_INITIALIZEREPOSITORYREQUEST_FILESENTRY']._serialized_options = b'8\001'
  _globals['_INITIALIZEREPOSITORYREQUEST']._serialized_start=21
  _globals['_INITIALIZEREPOSITORYREQUEST']._serialized_end=221
  _globals['_INITIALIZEREPOSITORYREQUEST_FILESENTRY']._serialized_start=177
  _globals['_INITIALIZEREPOSITORYREQUEST_FILESENTRY']._serialized_end=221
  _globals['_INITIALIZEREPOSITORYRESPONSE']._serialized_start=223
  _globals['_INITIALIZEREPOSITORYRESPONSE']._serialized_end=276
  _globals['_REPOSITORY']._serialized_start=278
  _globals['_REPOSITORY']._serialized_end=377
# @@protoc_insertion_point(module_scope)
